### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by ktavabi** [ktavabi/badbaby#15]
So close 😞

- [x] triage dataset @ktavabi 

> Reading /media/ktavabi/ALAYA/data/ilabs/badbaby/bad_212/inverse/AM_50-sss_eq_bad_212-ave.fif ...
>     Read a total of 1 projection items:
>         meg-ECG--0.04-0.04-PCA-01 (1 x 306)  idle
> Reading /media/ktavabi/ALAYA/data/ilabs/badbaby/bad_212/inverse/AM_50-sss_eq_bad_212-ave.fif ...
>     Read a total of 1 projection items:
>         meg-ECG--0.04-0.04-PCA-01 (1 x 306)  idle
> Traceback (most recent call last):
>   File "/home/ktavabi/Github/badbaby/badbaby/processing/run_mnefun.py", line 101, in <module>
>     mnefun.do_processing(
>   File "/home/ktavabi/Github/mnefun/mnefun/_mnefun.py", line 522, in do_processing
>     outs[ii] = func(p, subjects, structurals, run_indices)
>   File "/home/ktavabi/Github/mnefun/mnefun/_report.py", line 912, in gen_html_report
>     fig = this_evoked.plot_joint(
>   File "/home/ktavabi/Github/mne-python/mne/evoked.py", line 474, in plot_joint
>     return plot_evoked_joint(self, times=times, title=title, picks=picks,
>   File "/home/ktavabi/Github/mne-python/mne/viz/evoked.py", line 1453, in plot_evoked_joint
>     _plot_evoked(evoked, axes=ts_ax, show=False, plot_type='butterfly',
>   File "/home/ktavabi/Github/mne-python/mne/viz/evoked.py", line 347, in _plot_evoked
>     _plot_lines(evoked.data, info, picks, fig, axes, spatial_colors, unit,
>   File "/home/ktavabi/Github/mne-python/mne/viz/evoked.py", line 431, in _plot_lines
>     _check_if_nan(D)
>   File "/home/ktavabi/Github/mne-python/mne/utils/check.py", line 442, in _check_if_nan
>     raise ValueError("Some of the values {} are NaN.".format(msg))
> ValueError: Some of the values  to be plotted are NaN.

**Comment by larsoner** [comment]
This is also a mnefun issue -- it shouldn't try to plot if `nave=0` as it almost certainly is in this case, or maybe better it should just make a blank plot. I'll probably implement that with some "No valid epochs" text so that it's clear what's going on
